services:
  frontend:
    build:
      context: .
      dockerfile: srcs/docker/frontend/Dockerfile
    ports:
      - "3000:3000"
      - "8081:80"
    depends_on:
      - backend
    volumes:
      - ./public/avatars:/app/avatars
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: srcs/docker/backend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./srcs/backend/src:/app/src
      - ./public/avatars:/app/public/avatars
    restart: unless-stopped