export { landingHTML } from './landing.js';
export { signInHTML } from './signIn.js';
export { signUpHTML } from './signUp.js';
export { leaderboardHTML } from './leaderboard.js';
export { friendListHTML } from './friendList.js';
export { mainMenuHTML } from './mainMenu.js';
export { matchmakingHTML } from './matchmaking.js'
export { gameHTML } from './game.js';
export { game3HTML } from './game3.js';